apiVersion: v1
kind: Secret
metadata:
  name: kuma-secrets
type: Opaque
stringData:
  redis-password: 
  danbooru-user: 
  danbooru-api-key: 
  openai-api-key: 
  postgres-host: 
  postgres-username: 
  postgres-password: 
  postgres-database: 
  discord-token: 
  discord-mod-role-id: 
  discord-admin-id: 
  discord-moon-guild-id: 
  telegram-access-token: 
  telegram-admin-id: 
  twitch-channel: 
  twitch-username: 
  twitch-access-token: 
---
apiVersion: v1
kind: Secret
metadata:
  name: wiki-secrets
type: Opaque
stringData:
  mw-email: 
  mw-email-password: 
  mw-secret-key: 
  mw-upgrade-key: 
  postgres-host: 
  postgres-port: 
  postgres-username: 
  postgres-password: 
  postgres-database: 
  postgres-schema: 
  discord-webhook-url: 
---
apiVersion: v1
kind: Secret
metadata:
  name: backup-cronjob-secrets
type: Opaque
stringData:
  aws-s3-bucket-databases: 
  aws-s3-bucket-directories: 
  aws-access-key-id: 
  aws-secret-access-key: 
  postgres-host: 
  postgres-port: 
  postgres-username: 
  postgres-password: 
---
apiVersion: v1
kind: Secret
metadata:
  name: mimir-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username:
  password: